services:
  steam-scrds:
    build:
      context: .
      dockerfile: dockerfile
      args:
        RCON_PASSWORD: TestPassword
    image: steam-scrds:local
    ports:
      - "${SERVER_PORT:-27015}:27015/tcp"
      - "${SERVER_PORT:-27015}:27015/udp"
